/**
 * src/modules/publicPortfolio.js
 * A sanitized, high-end view of the portfolio for external stakeholders.
 */
import { stateManager } from '../state.js';
import { formatters } from '../utils/formatters.js';

export const publicPortfolio = {
    render() {
        const container = document.getElementById('view-public-portfolio');
        if (!container) return;

        const state = stateManager.get();
        const properties = state.properties || [];
        
        // Calculate Public Stats (Sanitized)
        const totalUnits = properties.reduce((sum, p) => sum + (parseInt(p.units) || 0), 0);
        const portfolioValue = properties.reduce((sum, p) => sum + (parseFloat(p.valuation) || 0), 0);

        container.innerHTML = `
            <div class="p-8 max-w-6xl mx-auto">
                <div class="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-gray-200 pb-8 mb-8 gap-4">
                    <div>
                        <h1 class="text-4xl font-black text-slate-900 tracking-tighter uppercase">
                            Track Record <span class="text-orange-600">/</span> ${state.settings?.companyName || 'Summit Capital'}
                        </h1>
                        <p class="text-slate-500 font-medium mt-1">Verified Real Estate Holdings & Performance</p>
                    </div>
                    <button id="share-portfolio" class="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-full font-bold text-sm hover:bg-slate-800 transition-all shadow-lg">
                        <i class="fa fa-share-nodes"></i> Copy Share Link
                    </button>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
                    <div class="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm text-center">
                        <p class="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2">Assets Managed</p>
                        <p class="text-4xl font-black text-slate-900">${properties.length}</p>
                    </div>
                    <div class="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm text-center">
                        <p class="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2">Total Door Count</p>
                        <p class="text-4xl font-black text-slate-900">${totalUnits}</p>
                    </div>
                    <div class="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm text-center">
                        <p class="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2">Portfolio AUM</p>
                        <p class="text-4xl font-black text-slate-900">${formatters.compact(portfolioValue)}</p>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                    ${this.renderPublicCards(properties)}
                </div>

                <footer class="mt-20 py-10 border-t border-gray-100 text-center">
                    <p class="text-xs font-bold text-gray-400 uppercase tracking-widest">
                        Confidential Information • Generated by Summit CRM
                    </p>
                </footer>
            </div>
        `;

        this.initListeners();
    },

    renderPublicCards(properties) {
        if (properties.length === 0) return `<p class="col-span-full text-center py-20 text-gray-400">No public assets listed.</p>`;

        return properties.map(p => `
            <div class="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden group hover:shadow-xl transition-all duration-500">
                <div class="h-48 bg-slate-100 flex items-center justify-center relative overflow-hidden">
                    <i class="fa fa-building text-6xl text-slate-200 group-hover:scale-110 transition-transform duration-700"></i>
                    <div class="absolute top-4 right-4 bg-white/90 backdrop-blur px-3 py-1 rounded-full text-[10px] font-black text-slate-900 uppercase">
                        ${p.units} Units
                    </div>
                </div>
                <div class="p-8">
                    <h3 class="text-2xl font-black text-slate-900 mb-2">${p.name}</h3>
                    <p class="text-sm font-bold text-orange-600 uppercase tracking-widest mb-6">${p.owning_llc || 'Holding Entity'}</p>
                    
                    <div class="grid grid-cols-2 gap-6 pt-6 border-t border-gray-50">
                        <div>
                            <p class="text-[10px] font-black text-gray-400 uppercase mb-1">Asset Value</p>
                            <p class="text-lg font-bold text-slate-900">${formatters.compact(p.valuation)}</p>
                        </div>
                        <div>
                            <p class="text-[10px] font-black text-gray-400 uppercase mb-1">Performance</p>
                            <p class="text-lg font-bold text-emerald-600">${p.occupancy}% Occupied</p>
                        </div>
                    </div>
                </div>
            </div>
        `).join('');
    },

    initListeners() {
        const shareBtn = document.getElementById('share-portfolio');
        if (shareBtn) {
            shareBtn.onclick = () => {
                const url = window.location.href;
                navigator.clipboard.writeText(url);
                shareBtn.innerHTML = `<i class="fa fa-check"></i> Link Copied!`;
                setTimeout(() => {
                    shareBtn.innerHTML = `<i class="fa fa-share-nodes"></i> Copy Share Link`;
                }, 2000);
            };
        }
    }
};